services:
  database:
    image: postgres:latest
    shm_size: 128MB
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    secrets:
      - postgres_password
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_DB=file-storage-db

  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD_FILE=/run/secrets/minio_root_password
    volumes:
      - ./minio/data:/data
    secrets:
      - minio_root_password
    command: server /data --console-address ":9001"

secrets:
  postgres_password:
    file: ./secrets/.psql_password
  minio_root_password:
    file: ./secrets/.minio_root_password

volumes:
  postgres_data: